# Generated by Django 4.1.7 on 2023-02-28 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Celebrity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя Фамилия')),
                ('born_date', models.DateField(verbose_name='Дата рождения')),
                ('character', models.CharField(max_length=50, verbose_name='Характер')),
                ('energy', models.CharField(max_length=50, verbose_name='Энергия')),
                ('interest', models.CharField(max_length=50, verbose_name='Интерес')),
                ('logic', models.CharField(max_length=50, verbose_name='Логика')),
                ('work', models.CharField(max_length=50, verbose_name='Знак труда')),
                ('lucky', models.CharField(max_length=50, verbose_name='Везение')),
                ('sence_humor', models.CharField(max_length=50, verbose_name='Чувство юмора')),
                ('memory', models.CharField(max_length=50, verbose_name='Память')),
            ],
        ),
    ]
