# Generated by Django 4.1.7 on 2023-02-28 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celebrities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='celebrity',
            name='health',
            field=models.CharField(default=0, max_length=50, verbose_name='Интерес'),
            preserve_default=False,
        ),
    ]
